### ISSUE TITLE
Case sensitive auto completion for tags

### ISSUE THREAD

**Issue by moon6pence** [clvrobj/Pinboard-Plus#41] opened 2017-12-21 10:05 UTC
Hello, thanks for good app for pinboard. 

I have been using tags with pascal style, like this: Play Recipes Apps 
However, auto completion of tags suggests me only lower case of tags and it's even harder to just type case sensitive tag. It automatically changes tags to lower case. 

Is it possible to use tag not to be forced as lower case?

**Comment by jorge0136** [comment] 2019-02-19 02:31
I believe this is being caused by a handful of `toLowerCase()` calls. Namely in `app/scripts/keywords_suggestions.js` and `app/scripts/popup.js`. 

Is there a reason to enforce lowercase @clvrobj ? If it's a preference for some, can we toggle this behaviour with an option, similar to how `Private checkbox checked by default` works?

**Comment by clvrobj** [comment] 2019-02-21 08:49
Thanks, guys.
The lowercase is just for matching the input tag. 
I got an idea to improve it, will give it a try.

**Comment by clvrobj** [comment] 2019-02-24 20:57
Fixed by #50 and new package released today.

**Closed by clvrobj** 2019-02-24 20:57 UTC
